# Generated by Django 4.1.3 on 2023-01-18 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_name_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
